networks:
  cheonil:
    name: cheonil
    driver: bridge
volumes:
  v-db:
services:
  db:
    container_name: db
    image: mariadb:11.5.2
    volumes:
      - v-db:/var/lib/mysql
    ports:
      - 3307:3306
    command: [--lc_time_names, ko_KR]
    environment:
      MYSQL_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: nice2122!
      MYSQL_DATABASE: cheonil
      TZ: Asia/Seoul
    restart: always
    networks:
      - cheonil
  cheonil-server:
    container_name: cheonil-server
    image: banhyungil/cheonil-restaurant-node
    restart: always
    ports:
      - 8000:8000
      - 8100:8100
    depends_on:
      - db
    environment:
      PORT: 8000
      WS_PORT: 8100
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: cheonil
      DB_USER: root
      DB_PWD: nice2122!
    networks:
      - cheonil
  cheonil-front:
    container_name: cheonil-front
    image: banhyungil/cheonil-restaurant
    ports:
      - 80:80
    depends_on:
      - cheonil-server
    environment:
      - API_IP=cheonil-server
      - API_PORT=8000
    restart: always
    networks:
      - cheonil

  