version: '3.1'
#
networks:
  cheonil:
    name: cheonil
    driver: bridge
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - /d/docker-compose/mount:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: cheonildb
      MYSQL_ROOT_HOST: '%'
    networks:
      - cheonil